### ISSUE TITLE
Adicionar nome como colaborador

### ISSUE THREAD

**Issue by Lukas-Oliveira** [Oli-Lukas/GCMS-Lucas-Oliveira#1]
Professor @ramidedantas, solicito que o senhor coloque o seu nome como colaborador no arquivo [Readme.md](https://github.com/Oli-Lukas/GCMS-Lucas-Oliveira/edit/main/README.md).

**Comment by ramidedantas** [comment]
@Oli-Lukas nome adicioando, pode fechar issue.
